# 1.0.5.0
# created: 05 Feb 2022
# updated: 05 Oct 2022
# update checkout to v3.0.2
# Create Indexes from Markdown
# https://github.com/DaanV2/Markdown-Action-Create-Indexes

name: Create markdown indexes

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@latest
      - uses: actions/checkout@main
      # - uses: DaanV2/Markdown-Action-Create-Indexes@latest
      - uses: DaanV2/Markdown-Action-Create-Indexes@main
        with: 
          folder: ${{github.workspace}}/docs/

      - name: Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "39887717+zer0Kerbal@users.noreply.github.com"
          git config --global user.name "zer0Kerbal"
          git add .
          git commit -m "auto: Generated markdown indexes"
          git push